name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-test-docker:
    name: Build Docker Image (Local Test Only)
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image locally
        run: |
          echo "Building Docker image (no push)..."
          docker build -t networksecurity:test .

      - name: Test Docker image locally
        run: |
          echo "Running Docker container (local test)..."
          docker run -d -p 8080:8080 --name networksecurity_test networksecurity:test
          docker ps

      - name: Stop and remove test container
        run: |
          docker stop networksecurity_test
          docker rm networksecurity_test

      - name: Clean up Docker images
        run: |
          docker rmi networksecurity:test || echo "No local image to remove"
          docker system prune -f
